### ISSUE TITLE
[changelog] links property is ignored

### ISSUE THREAD

**Issue by dmurat** [jreleaser/jreleaser#114]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1. Configure changelog `links` property to true
2. Generate a changelog.

### Expected Behaviour
Full markdown links should be generated for abbreviated commit hashes.

### Actual Behaviour
Raw abbreviated commit hashes are generated.

### Environment Information
- **JReleaser Version:** 0.3.0-SNAPSHOT
- JReleaser is used via jbang

I believe the problem is in ChangelogGenerator.formatChangelog method, where `links` property is not used:
https://github.com/jreleaser/jreleaser/blob/83ba6c7c264f942d874c99439b46e7a82e7a4ed9/sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java#L250

Tnx
