### ISSUE TITLE
jreleaser init fails

### ISSUE THREAD

**Issue by jeffmaury** [jreleaser/jreleaser#1141]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. jreleaser init

### Expected Behaviour

Should run without error

### Actual Behaviour

```
java.lang.IllegalArgumentException: Unsupported file format. Must be one of [json|toml|yml]
        at org.jreleaser.engine.init.Init.execute(Init.java:53)
        at org.jreleaser.cli.Init.execute(Init.java:53)
        at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
        at org.jreleaser.cli.Init.call(Init.java:30)
        at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.jreleaser.cli.Main.execute(Main.java:73)
        at org.jreleaser.cli.Main.run(Main.java:58)
        at org.jreleaser.cli.Main.main(Main.java:49)
```

### Environment Information

- **Operating System**: Win11Pro
- **JReleaser Version:** 1.4.0
- **JDK Version:** openjdk version "17.0.4.1" 2022-08-12

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by jeffmaury** [comment]
In that case the help message is wrong as it seems all arguments are optional

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
