### ISSUE TITLE
Error when deploying parent pom with children modules

### ISSUE THREAD

**Issue by seinecle** [jreleaser/jreleaser#1293]
### Task List

- [ ] Steps to reproduce provided
- [X ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce
Works fine for a standalone project, hits issues for a parent pom with children modules
Publish to Maven central using the Github action and further instructions in https://maciejwalkowiak.com/blog/guide-java-publish-to-maven-central/

The repo: https://github.com/seinecle/umigon-family

### Expected Behaviour
Should publish the parent pom and the children modules to Maven Central

### Actual Behaviour
The Github actions interrupts with this error:

```
JReleaser Maven Plugin 1.3.1. Consider becoming a patron at https://www.patreon.com/aalmiray
JReleaser Maven Plugin 1.3.1. Consider becoming a patron at https://www.patreon.com/aalmiray
[INFO] JReleaser 1.3.1
[INFO] JReleaser 1.3.1
[INFO]   - basedir set to /home/runner/work/umigon-family/umigon-family
[INFO]   - basedir set to /home/runner/work/umigon-family/umigon-family
[INFO] Loading variables from /home/runner/.jreleaser/config.properties
Warning:  Variables source /home/runner/.jreleaser/config.properties does not exist
[INFO] Validating configuration
[INFO] Loading variables from /home/runner/.jreleaser/config.properties
Warning:  Variables source /home/runner/.jreleaser/config.properties does not exist
[INFO] Validating configuration
[INFO] Project version set to 0.218
[INFO] Project version set to 0.218
[INFO] Release is not snapshot
[INFO] Timestamp is 2023-03-23T23:23:11.001154Z
[INFO] HEAD is at 2ba9ce9
[INFO] Platform is linux-x86_64
[INFO] Release is not snapshot
[INFO] Timestamp is 2023-03-23T23:23:11.001154Z
[INFO] HEAD is at 2ba9ce9
[INFO] Platform is linux-x86_64
[INFO] dry-run set to false
[INFO] dry-run set to false
[INFO] Deploying all staged artifacts
[INFO] Deploying all staged artifacts
[INFO]   [nexus2] Deploying to maven-central
[INFO]   [nexus2] Deploying to maven-central
Error:   [nexus2] PomChecker 1.3.0. Consider becoming a patron at https://www.patreon.com/aalmiray
Error:   [nexus2] Exception in thread "main" java.lang.AbstractMethodError: Receiver class org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayoutEx does not define or inherit an implementation of the resolved method 'abstract java.util.List getChecksumAlgorithmFactories()' of interface org.eclipse.aether.spi.connector.layout.RepositoryLayout.
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:230)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:262)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:318)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:299)
	at org.apache.maven.project.DefaultProjectBuilder.initParent(DefaultProjectBuilder.java:960)
	at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:680)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:124)
	at org.kordamp.maven.checker.cli.internal.PomParser.createMavenProject(PomParser.java:99)
	at org.kordamp.maven.checker.cli.internal.PomParser.createMavenProject(PomParser.java:66)
	at org.kordamp.maven.checker.cli.CheckMavenCentral.execute(CheckMavenCentral.java:45)
	at org.kordamp.maven.checker.cli.AbstractCommand.call(AbstractCommand.java:90)
	at org.kordamp.maven.checker.cli.CheckMavenCentral.call(CheckMavenCentral.java:30)
	at org.kordamp.maven.checker.cli.AbstractCommand.call(AbstractCommand.java:32)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.kordamp.maven.checker.cli.Main.execute(Main.java:69)
	at org.kordamp.maven.checker.cli.Main.run(Main.java:55)
	at org.kordamp.maven.checker.cli.Main.main(Main.java:47)
[INFO] Writing output properties to umigon-stopwords/target/jreleaser/output.properties
Error:  JReleaser failed after 29.894 s
```
### Environment Information

- **Operating System**: Linux on Github actions
- **JReleaser Version:** 1.5.1
- **JDK Version:** 11
