### ISSUE TITLE
[assemble] NPE when using assembly without release

### ISSUE THREAD

**Issue by bmarwell** [jreleaser/jreleaser#1517]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. configure the maven plugin like so (I did put this into my nested module):
```xml
      <plugin>
        <groupId>org.jreleaser</groupId>
        <artifactId>jreleaser-maven-plugin</artifactId>
        <version>1.8.0</version>
        <inherited>false</inherited>
        <configuration>
          <jreleaser>
            <release>
              <github>
                <enabled>true</enabled>
              </github>
            </release>
            <assemble>
              <javaArchive>
                <cfggenerator>
                  <active>ALWAYS</active>
                  <formats>
                    <format>ZIP</format>
                  </formats>
                  <mainJar>
                    <path>${project.build.directory}/${project.build.finalName}.jar</path>
                  </mainJar>
                </cfggenerator>
              </javaArchive>
            </assemble>
          </jreleaser>
        </configuration>
        <executions>
          <execution>
            <id>assemble-modular-distribution</id>
            <goals>
              <goal>assemble</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>
```
2. execute `mvn package`

### Expected Behaviour

assembly exists

### Actual Behaviour

```
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal (ConcurrentHashMap.java:1016)
    at java.util.concurrent.ConcurrentHashMap.put (ConcurrentHashMap.java:1011)
    at java.util.Properties.put (Properties.java:1340)
    at org.jreleaser.model.internal.JReleaserContext.report (JReleaserContext.java:960)
    at org.jreleaser.workflow.WorkflowImpl.doExecute (WorkflowImpl.java:164)
    at org.jreleaser.workflow.WorkflowImpl.execute (WorkflowImpl.java:52)
    at org.jreleaser.maven.plugin.JReleaserAssembleMojo.doExecute (JReleaserAssembleMojo.java:73)
    at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute (AbstractJReleaserMojo.java:109)
    at org.jreleaser.maven.plugin.JReleaserAssembleMojo.execute (JReleaserAssembleMojo.java:34)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
```

Code which leads to this:

```
            if (releaser.isReleaseSupported()) {
                props.put(KEY_RELEASE_NAME, releaser.getEffectiveReleaseName());
                props.put(KEY_MILESTONE_NAME, releaser.getMilestone().getEffectiveName());
            }
```

### Environment Information

- **Operating System**: any
- **JReleaser Version:** 1.8.0
- **JDK Version:** any (used Semeru 20.0.2)

**Comment by bmarwell** [comment]
As said in chat, I think the release should not be needed when just invoking assembly.

This helps:

setting a release target, e.g. github -> enabled -> add owner, name, host

If I add `<skipRelease>true</skipRelease>` to the java archive, I get this, another NPE:

```
[INFO] Validating configuration
[INFO] Strict mode set to false
[ERROR] == JReleaser ==
[ERROR] java.lang.NullPointerException: Cannot invoke "org.jreleaser.model.internal.assemble.JavaArchiveAssembler.setName(java.lang.String)" because the return value of "java.util.Map$Entry.getValue()" is null
```

**Comment by aalmiray** [comment]
`<skipRelease>` can not be set on `<javaArchive>`. It should be set on the releaser, in this case, `<github>`.

**Comment by aalmiray** [comment]
Cannot reproduce with exact instructions. Even more, the following also did not trigger the NPE

1. git clone https://github.com/jreleaser/helloworld-java-bin.git
2. Edit `jreleaser.yml` and comment out the `release` section
3. Build the project with `mvnw verify`
4. Set  project version with env var `export JRELEASER_PROJECT_VERSION=1.0.0-SNAPSHOT`
5. Check assembly configuration with `jreleaser config --assembly`
```
$ jreleaser config --assembly
[INFO]  JReleaser 1.8.0
[INFO]  Configuring with jreleaser.yml
[INFO]    - basedir set to /Users/aalmiray/dev/github/helloworld-java-bin
[INFO]    - outputdir set to /Users/aalmiray/dev/github/helloworld-java-bin/out/jreleaser
[INFO]  Reading configuration
[INFO]  git-root-search set to false
[INFO]  Loading variables from /Users/aalmiray/.jreleaser/config.toml
[INFO]  Validating configuration
[INFO]  Strict mode set to false
[INFO]  Project version set to 1.0.0-SNAPSHOT
[INFO]  Release is snapshot
[INFO]  Timestamp is 2023-10-25T15:17:02.60077+02:00
[INFO]  HEAD is at 8b592aa
[INFO]  Platform is osx-x86_64
hooks:
    enabled: false
    active: NEVER
    command:
        enabled: false
        active: NEVER
    script:
        enabled: false
        active: NEVER
 
project:
    name: helloworld
    version: 1.0.0-SNAPSHOT
    versionPattern: SEMVER
    snapshot:
        enabled: true
        pattern: .*-SNAPSHOT
        label: early-access
        fullChangelog: false
    description: HelloWorld in Java
    longDescription: HelloWorld in Java
    license: APACHE-2.0
    inceptionYear: 2023
    copyright: 2023 Andres Almiray
    authors:
        Andres Almiray
    stereotype: CLI
    links:
        homepage: https://github.com/jreleaser/helloworld-java-bin
        documentation: https://github.com/jreleaser/helloworld-java-bin
        license: https://github.com/jreleaser/helloworld-java-bin/blob/main/LICENSE
        bugTracker: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/issues
        vcsBrowser: https://{{repoHost}}/{{repoOwner}}/{{repoName}}
    extraProperties:
        versionMajor: 1
        versionMinor: 0
        versionPatch: 0
        versionNumber: 1.0.0
        versionTag: SNAPSHOT
        versionWithUnderscores: 1_0_0_SNAPSHOT
        versionWithDashes: 1-0-0-SNAPSHOT
        versionNumberWithUnderscores: 1_0_0
        versionNumberWithDashes: 1-0-0
        effectiveVersionWithUnderscores: early_access
        effectiveVersionWithDashes: early-access
 
release:
    github:
        enabled: true
        host: github.com
        owner: jreleaser
        name: helloworld-java-bin
        username: jreleaser
        token: ************
        artifacts: true
        files: true
        checksums: true
        catalogs: true
        signatures: true
        repoUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}
        repoCloneUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}.git
        commitUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/commits
        srcUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/blob/{{repoBranch}}
        downloadUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/download/{{tagName}}/{{artifactFile}}
        releaseNotesUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/tag/{{tagName}}
        latestReleaseUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases/latest
        issueTrackerUrl: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/issues
        tagName: v{{projectVersion}}
        releaseName: Release {{tagName}}
        branch: main
        branchPush: main
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        sign: false
        skipTag: false
        skipRelease: false
        overwrite: true
        update:
            enabled: false
        apiEndpoint: https://api.github.com
        connectTimeout: 20
        readTimeout: 60
        changelog:
            enabled: true
            append:
                enabled: false
            links: false
            skipMergeCommits: false
            sort: DESC
            hide:
            contributors:
        milestone:
            name: {{tagName}}
            close: true
        issues:
            enabled: false
            comment: 🎉 This issue has been resolved in `{{tagName}}` ([Release Notes]({{releaseNotesUrl}}))
            label:
                name: released
                color: #FF0000
                description: Issue has been released
        prerelease:
            enabled: true
        draft: false
        releaseNotes:
            enabled: false
 
checksum:
    name: checksums.txt
    individual: false
    algorithms:
        SHA_256
    artifacts: true
    files: true
 
announce:
    enabled: true
 
download:
    enabled: true
 
assemble:
    enabled: true
    active: ALWAYS
    javaArchive:
        helloworld:
            enabled: true
            exported: true
            active: ALWAYS
            stereotype: CLI
            archiveName: {{distributionName}}-{{projectVersion}}
            formats:
                ZIP
            options:
                timestamp: 2023-03-12T12:12:32+01:00[GMT+01:00]
                longFileMode: ERROR
                bigNumberMode: ERROR
            executable:
                name: helloworld
                windowsExtension: bat
            mainJar:
                enabled: true
                active: ALWAYS
                path: target/{{distributionName}}-{{projectVersion}}.jar
            java:
                mainClass: org.jreleaser.examples.HelloWorld
            templateDirectory: src/jreleaser/assemblers/helloworld/java-archive
            fileSets:
                fileSet 0:
                    enabled: true
                    active: ALWAYS
                    input: .
                    includes:
                        LICENSE
 
deploy:
    enabled: true
    maven:
        enabled: true
        pomchecker:
            version: 1.9.0
            failOnWarning: true
            failOnError: true
 
upload:
    enabled: true
 
catalog:
    enabled: true
    sbom:
        enabled: true
 
[INFO]  Writing output properties to out/jreleaser/output.properties
```
6. Assemble the archive with `jreleaser assemble`
```
$ jreleaser assemble
[INFO]  JReleaser 1.8.0
[INFO]  Configuring with jreleaser.yml
[INFO]    - basedir set to /Users/aalmiray/dev/github/helloworld-java-bin
[INFO]    - outputdir set to /Users/aalmiray/dev/github/helloworld-java-bin/out/jreleaser
[INFO]  Reading configuration
[INFO]  git-root-search set to false
[INFO]  Loading variables from /Users/aalmiray/.jreleaser/config.toml
[INFO]  Validating configuration
[INFO]  Strict mode set to false
[INFO]  Project version set to 1.0.0-SNAPSHOT
[INFO]  Release is snapshot
[INFO]  Timestamp is 2023-10-25T15:17:08.738048+02:00
[INFO]  HEAD is at 8b592aa
[INFO]  Platform is osx-x86_64
[INFO]  dry-run set to false
[INFO]  Assembling distributions
[INFO]    [assemble] Assembling all distributions
[INFO]      [java-archive] assembling helloworld distribution
[INFO]      [java-archive] - helloworld-1.0.0-SNAPSHOT.zip
[INFO]  Writing output properties to out/jreleaser/output.properties
[INFO]  JReleaser succeeded after 0.126 s
```

Archive was successfully assembled
```
$ unzip -l out/jreleaser/assemble/helloworld/java-archive/helloworld-1.0.0-SNAPSHOT.zip 
Archive:  out/jreleaser/assemble/helloworld/java-archive/helloworld-1.0.0-SNAPSHOT.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    11357  03-12-2023 12:12   helloworld-1.0.0-SNAPSHOT/LICENSE
     4197  03-12-2023 12:12   helloworld-1.0.0-SNAPSHOT/bin/helloworld
     1785  03-12-2023 12:12   helloworld-1.0.0-SNAPSHOT/bin/helloworld.bat
     3815  03-12-2023 12:12   helloworld-1.0.0-SNAPSHOT/lib/helloworld-1.0.0-SNAPSHOT.jar
---------                     -------
    21154                     4 files
```

**Comment by bmarwell** [comment]
It was only one project. The same setup worked on another project. Can't create a reproducer. Closing for now.
