### ISSUE TITLE
Can not run 'jbang jreleaser-snapshot@jreleaser' on Windows

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#154]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Launch `jbang jreleaser-snapshot@jreleaser -V` on a Windows environment

### Expected Behaviour

The current JReleaser version should be printed out.

### Actual Behaviour

An error is thrown by Jbang when assembling the JAR.

See https://github.com/jreleaser/jreleaser/issues/149#issuecomment-843102583

### Environment Information

- **Operating System**: Windows
- **JReleaser Version:** N/A
- **JDK Version:** N/A

**Comment by aalmiray** [comment]
See https://github.com/jbangdev/jbang/issues/161

**Comment by aalmiray** [comment]
Bug has been identified and fixed https://github.com/jbangdev/jbang/pull/884

**Comment by aalmiray** [comment]
Closing as this was a bug in Jbang.
