### ISSUE TITLE
NPE on jreleaser-maven-plugin if no scm information is available

### ISSUE THREAD

**Issue by bmarwell** [jreleaser/jreleaser#1678]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a project without yaml files, mvn config only
2. do not add (or remove) scm info
3. configure a distribution (javaArchive)
4. run packagee

### Expected Behaviour

Packaging done OR give a nice error message that scm info is required

### Actual Behaviour

scm branch is assumed to be set, NPE at https://github.com/jreleaser/jreleaser/blob/ce421ade958878c2f3c73f9f58cbc4e90e5b81a4/core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/JReleaserContext.java#L999

### Workaround and solution

set the scm information.

### Environment Information

- **Operating System**: any
- **JReleaser Version:** 1.12.0
- **JDK Version:** 21

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

```
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal (ConcurrentHashMap.java:1011)
    at java.util.concurrent.ConcurrentHashMap.put (ConcurrentHashMap.java:1006)
    at java.util.Properties.put (Properties.java:1346)
    at org.jreleaser.model.internal.JReleaserContext.report (JReleaserContext.java:999)
    at org.jreleaser.workflow.WorkflowImpl.doExecute (WorkflowImpl.java:178)
    at org.jreleaser.workflow.WorkflowImpl.execute (WorkflowImpl.java:54)
    at org.jreleaser.maven.plugin.JReleaserAssembleMojo.doExecute (JReleaserAssembleMojo.java:73)
    at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute (AbstractJReleaserMojo.java:109)
    at org.jreleaser.maven.plugin.JReleaserAssembleMojo.execute (JReleaserAssembleMojo.java:34)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:904)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:281)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:204)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
```

**Comment by bmarwell** [comment]
Oh it is actually an old bug,

```
            <release>
              <github>
                <skipRelease>true</skipRelease>
                <enabled>false</enabled>
              </github>
            </release>
```

this will cause the NPE, not the Maven SCM info.

**Comment by aalmiray** [comment]
Two things:
1. Which jreleaser goal was invoked? The `assemble` goal does not require SCM information. 
2. If no active releaser is resolved then some goals should fail with a validation error, not an NPE.

**Comment by aalmiray** [comment]
The following configuration is enough to trigger the error when invoking `mvn jreleaser:assemble`:

```xml
<plugin>
  <groupId>org.jreleaser</groupId>
  <artifactId>jreleaser-maven-plugin</artifactId>
  <version>1.12.0</version>
  <configuration>
      <jreleaser>
          <project>
              <java>
                  <version>11</version>
                  <mainClass>org.jreleaser.examples.HelloWorld</mainClass>
              </java>
          </project>
          <assemble>
              <javaArchive>
                  <helloworld>
                      <active>ALWAYS</active>
                      <formats>
                        <format>ZIP</format>
                      </formats>
                      <fileSets>
                          <fileSet>
                              <input>.</input>
                              <includes>LICENSE</includes>
                          </fileSet>
                      </fileSets>
                      <mainJar>
                          <path>target/{{distributionName}}-{{projectVersion}}.jar</path>
                      </mainJar>
                  </helloworld>
              </javaArchive>
          </assemble>
      </jreleaser>
  </configuration>
</plugin>  
```

Note: Not `.git` directory is available in the source tree.

**Comment by bmarwell** [comment]
wow that was quick! Thanks @aalmiray !!! 👍🏻

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.13.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.13.0))
