### ISSUE TITLE
[build] Support Apple ARM64 Silicon (M1)

### ISSUE THREAD

**Issue by kensipe** [jreleaser/jreleaser#608]
Builds on Apple M1 machines fail based on lack of dependency support.   

```
* What went wrong:
Execution failed for task ':jreleaser-tool-provider:compileJava'.
> Failed to calculate the value of task ':jreleaser-tool-provider:compileJava' property 'javaCompiler'.
   > Unable to download toolchain matching these requirements: {languageVersion=9, vendor=any, implementation=vendor-specific}
      > Unable to download toolchain. This might indicate that the combination (version, architecture, release/early access, ...) for the requested JDK is not available.
         > Could not read 'https://api.adoptopenjdk.net/v3/binary/latest/9/ga/mac/aarch64/jdk/hotspot/normal/adoptopenjdk' as it does not exist.

```
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Buy an Apple MBP Pro / Max with Apple Silicon instead of your car or child's first year of tuition in college
2. Setup with Java 11 (support via Azul is pretty awesome: https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk)
3. Build:  `./gradlew test`

### Expected Behaviour

Successful build

### Actual Behaviour

Bad things

### Environment Information

- **Operating System**: Mac OS Monterey 12.0.1
- **JReleaser Version:** Tip of Main
- **JDK Version:**  Azul JDK 11 

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by kensipe** [comment]
This is likely an upstream issue to resolve... Adding for awareness and prioritization.

**Comment by aalmiray** [comment]
@kensipe this is a problem when building JReleaser from source. The build requires Gradle 6.9 which is setup to work with Java 8 up to 15. 

Do you need an osx-aarch64 build? we have one for the CLI ready for testing https://github.com/jreleaser/jreleaser/releases/tag/early-access

**Comment by aalmiray** [comment]
I see where the problem may be

https://github.com/jreleaser/jreleaser/blob/8a452563c86f358306601611cc7c0e77af98bf3e/apps/jreleaser-tool-provider/jreleaser-tool-provider.gradle#L79-L88

This instructs Gradle to download Java 9 which uses AdoptOpenJDK by default. Perhaps it will be better to switch to Java 11 compatibility and use Azul as vendor.

**Comment by aalmiray** [comment]
Update: https://github.com/jreleaser/jreleaser/commit/4362c41e9a3bae09d0af4ad43759b557ff6653e9

**Comment by kensipe** [comment]
great turn around!   I was planning on jumping on the contribution train and was looking for a way to build it.  But I also wanted to use the new Mac... thank you!   that fix was too easy... no I hang my head in shame :)    Great stuff!  thanks again.

**Comment by aalmiray** [comment]
Thanks @kensipe, we've got plenty of opportunities for contributions. Specifically M1 support would be great given that I've yet to get my hands on one of those puppies.
