### ISSUE TITLE
Error: jreleaser-maven-plugin and mail announcer error mail.host must not be blank

### ISSUE THREAD

**Issue by dhinojosa** [jreleaser/jreleaser#861]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

Create a maven-plugin-project using JReleaser that will define in the plugin the mail announcer.
One is configured here at the following repository at a certain branch location
https://github.com/dhinojosa/jreleaser-demo/tree/jreleaser-maven-plugin

### Expected Behaviour

The announcer should run as expected and send an email with a release

### Actual Behaviour

An error

```sh
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.1.0:announce (default-cli) on project basic-app: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.1.0:announce failed: JReleaser has not been properly configured.
[ERROR] mail.host must not be blank
```

### Environment Information

- **Operating System**: MacOSX
- **JReleaser Version:** 1.1.0
- **JDK Version:** 17

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.
