### ISSUE TITLE
[package] maven brew create formula with wrong ruby file

### ISSUE THREAD

**Issue by yoavgeva** [jreleaser/jreleaser#973]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

link for github repo https://github.com/yoavgeva/ferret

### Steps to Reproduce

create application with maven with app name of example

config packaging with homebrew (used tag of <formulaName> only changed in the class) 
use maven jrelease to release 

### Expected Behaviour

create tap repository Formula/example.rb with class in file of example

### Actual Behaviour

create tap repository Formula/app.rb with class of example

### Environment Information

- **Operating System**: mac
- **JReleaser Version:** 1.2.0
- **JDK Version:** 11

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by aalmiray** [comment]
I've looked at the linked repository and ran `mvn -Pnative,dist 7& mvn -Prelase jreleaser:config` and `mvn -Prelease jreleaser:prepare` and I still don't get what the problem is

config
```yaml
distributions:
    app:
        enabled: true
        active: always
        type: NATIVE_IMAGE
        executable:
            name: app
            windowsExtension: bat
        artifacts:
            artifact 0:
                path: /tmp/ferret/target/distributions/ferret-1.0.13-osx-x86_64.zip
                platform: osx-x86_64
        stereotype: none
        brew:
            enabled: true
            active: always
            continueOnError: false
            templateDirectory: src/jreleaser/distributions/app/brew
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            formulaName: ferret
            multiPlatform: false
            tap:
                enabled: true
                active: release
                owner: yoavgeva
                name: homebrew-tap
                tagName: ferret
                branch: HEAD
                username: yoavgeva
                token: ************
                commitMessage: {{distributionName}} {{tagName}}
            cask:
                enabled: false
```

The distribution name is set to `app`. The formula name is resolved to `ferret`. The name of the tap repository is the default value `homebrew-tap`. The generated formula looks like this

```ruby
class Ferret < Formula
  desc "Ferret - local pipelines"
  homepage "https://github.com/salesforce/ferret"
  url "https://github.com/yoavgeva/ferret/releases/download/v1.0.13/ferret-1.0.13-osx-x86_64.zip"
  version "1.0.13"
  sha256 "7190d637162b8ab431e68ccd456346adfcbb87c9292280f6f7611bb7a6ef4ef0"
  license "BSD 3-Clause"


  def install
    libexec.install Dir["*"]
    bin.install_symlink "#{libexec}/bin/app" => "app"
  end

  test do
    output = shell_output("#{bin}/app --version")
    assert_match "1.0.13", output
  end
end
```

**Comment by aalmiray** [comment]
Alright, on second look I think the problem is that the formula filename is set to `app.rb` when it should had been `ferret.rb`, right?

**Comment by yoavgeva** [comment]
@aalmiray yup

**Comment by aalmiray** [comment]
See https://docs.brew.sh/Formula-Cookbook#a-quick-word-on-naming

Code to be updated is at https://github.com/jreleaser/jreleaser/blob/e9661217550ca650962a81cbbb9a56abac28c6e7/core/jreleaser-engine/src/main/java/org/jreleaser/packagers/BrewPackagerProcessor.java#L223-L241

**Comment by roulpriya** [comment]
I like to work on this issue @aalmiray

**Comment by aalmiray** [comment]
OK! The trick is to respect the name mappings from Capitalized CamelCase to lower-kebab-case when  applicable 😁
